spring:
  application:
    name: receitar-io
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/spring-boot-h2-db
  jpa:
    hibernate:
      ddl-auto: update
  database-platform=org:
    hibernate:
      dialect: PostgreSQL95Dialect
server:
  port: 8081
